# Generated by Django 3.0.2 on 2020-03-07 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.DateTimeField(auto_now_add=True, null=True)),
                ('checkout', models.DateTimeField(auto_now_add=True, null=True)),
                ('break_fast', models.IntegerField(blank=True, null=True)),
                ('nights', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, max_length=400, null=True)),
                ('booking_type', models.PositiveIntegerField(choices=[(1, 'Guaranteed Reservation'), (2, 'Non–Guaranteed Reservation')])),
                ('booking_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customers')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Rooms')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
