# Generated by Django 3.0.2 on 2020-03-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(blank=True, null=True)),
                ('room_type', models.PositiveIntegerField(choices=[(1, 'Single'), (2, 'Double'), (3, 'Triple')])),
                ('price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_person', models.IntegerField(blank=True, null=True)),
                ('room_status', models.PositiveIntegerField(choices=[(1, 'OCCUPIED'), (2, 'STAYOVER'), (3, 'ON-CHANGE'), (4, 'DO-NOT-DISTURB'), (5, 'CLEANING-IN-PROGRESS'), (6, 'SLEEP-OUT'), (7, 'ON-QUEUE'), (8, 'SKIPPER'), (9, 'VACANT-AND-READY'), (10, 'OUT-OF-ORDER'), (11, 'OUT-OF-SERVICE'), (12, 'LOCK-OUT'), (13, 'DID-NOT-CHECK-OUT)'), (14, 'DUE-OUT'), (15, 'CHECK-OUT'), (16, 'LATE-CHECK-OUT')])),
                ('number_of_beds', models.IntegerField(blank=True, null=True)),
                ('locked', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
    ]
